patient_id: 'CC01'
current_experiment: 'center_out'
current_calibration: 'calibration'
bci_states:
  CC01:
    center_out: ['StimulusCode', 'cursorX', 'cursorY', 'Baseline', 'ResultCode']
    calibration: ['StimulusCode']
state_information:
  CC01:
    center_out:
      stimulus_state: 'StimulusCode'
      reached_state: 'ResultCode'
gain: 0.25
data_preprocessing:
  channel_labelling:
    channel_selection: 'all'
    channels:
      CC01:
        motor: ['chan66','chan67','chan68','chan69','chan70','chan74','chan75','chan76','chan77','chan78','chan84','chan85','chan86','chan91',
                                              'chan92','chan93','chan94', 'chan99','chan100','chan101','chan102','chan108','chan109','chan110','chan117','chan118',
                                              'chan125','chan126']
        sensory: ['chan71','chan72','chan79','chan80','chan87','chan88','chan95','chan96','chan103','chan104','chan112','chan120','chan128']
    elim_channels:
      CC01:
        channels: ['ainp1','ainp2','ainp3']
    bad_channels:
      CC01:
        channels: []
    grid_split:
      CC01: 
        split_indices: [65]

sessions:
  CC01:
    center_out:
      overt: 
        '20221027': ['S03', 'S04', 'S05', 'S06', 'S07']
        '20221104': ['S04', 'S05', 'S06', 'S07', 'S08']
        '20221108': ['S03', 'S04', 'S05', 'S06', 'S07']
        '20221111': ['S02', 'S03', 'S04', 'S05', 'S06']
      covert:
        '20221027': ['S08', 'S09']
        '20221104': ['S09', 'S10']
        '20221108': ['S08', 'S09']
        '20221111': ['S07', 'S08']
    calibration:
      '20221027': ['S01', 'S02', 'S03']
      '20221104': ['S01', 'S02']
      '20221108': ['S01', 'S02']
      '20221111': ['S01', 'S02']

grid_layout:
  CC01: [
    [["B121", "B122", "B123", "B124", "B125", "B126", "B127", "B128"],
     ["B113", "B114", "B115", "B116", "B117", "B118", "B119", "B120"],
     ["B105", "B106", "B107", "B108", "B109", "B110", "B111", "B112"],
     ["B97", "B98", "B99", "B100", "B101", "B102", "B103", "B104"],
     ["B89", "B90", "B91", "B92", "B93", "B94", "B95", "B96"],
     ["B81", "B82", "B83", "B84", "B85", "B86", "B87", "B88"],
     ["B73", "B74", "B75", "B76", "B77", "B78", "B79", "B80"],
     ["B65", "B66", "B67", "B68", "B69", "B70", "B71", "B72"]], 

    [["A57", "A58", "A59", "A60", "A61", "A62", "A63", "A64"],
     ["A49", "A50", "A51", "A52", "A53", "A54", "A55", "A56"],
     ["A41", "A42", "A43", "A44", "A45", "A46", "A47", "A48"],
     ["A33", "A34", "A35", "A36", "A37", "A38", "A39", "A40"],
     ["A25", "A26", "A27", "A28", "A29", "A30", "A31", "A32"],
     ["A17", "A18", "A19", "A20", "A21", "A22", "A23", "A24"],
     ["A9", "A10", "A11", "A12", "A13", "A14", "A15", "A16"],
     ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8"]]]

model_data_params:
  window_size: 10 # samples
  shift: 1 # samples
  pre_stimulus_time: 0.5 # seconds
  post_completion_time: 0 # seconds

  center_out:
    sel_split_type: 'leave_session_out' # leave_day_out, leave_session_out, leave_trial_out
    sel_session_type: 'overt'
    split_types:
      leave_day_out:
        leave_out: 1
        randomized: True
        random_seed: 1234
      leave_session_out:
        leave_out: 5
        randomized: True
        random_seed: 1234
      leave_trial_out:
        leave_out: 20
        randomized: True
        random_seed: 1234